name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # lub inna gałąź, której używasz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Zaktualizowana wersja

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Upewnij się, że używasz Node.js 16 lub 20
      with:
        node-version: '16'  # lub '20', jeśli chcesz przejść na Node 20

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v4  # Zaktualizowana wersja
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # lub inny katalog, który chcesz opublikować

